version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./server:/app
      - /app/node_modules